events {
    worker_connections 1024;
    }

http {
    log_format text '[$time_local] IP: $remote_addr | Request: "$request" | Status: $status | Time: ${request_time}s';

    server {
        listen 80;
        access_log /var/log/nginx/http.log text;

        location / {
            proxy_pass http://main:8000;
            proxy_set_header Host $host;
            proxy_set_header x_Real-IP $remote_addr;

        }

    }
}
