server {
    listen 80;

    location / {
        proxy_pass http://main:8000;
    }

    location /input/ {
        proxy_pass http://input:8000;
    }

    location /stat/ {
        proxy_pass http://stat:8000;
    }
}
