# Generated by Django 6.0.5 on 2026-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='city',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Город'),
        ),
    ]
